Proyecto/Models/Score.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proyecto.Models
{
    public class Score
    {
        [Key]
        public int IdScore { get; set; }

        public string StudentId { get; set; }

        public int IdSchedule { get; set; }

        //public Schedule Schedules { get; set; }

        //public AspNetUser AspNetUsers { get; set; }

        [Display(Name = "Nota")]
        public double StudentScore { get; set; }

    }

    public class StudentViewModel
    {
        [Required]
        public string StudentId { get; set; }

        [Required]
        public int ScheduleId { get; set; }

        [Required]
        [Display(Name= "Nombre")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Correo")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Teléfono")]
        public string Phone { get; set; }

        [Required]
        public int ScoreId { get; set; }
    }

    public class ScoreViewModel
    {
        [Required]
        public int ScoreId { get; set; }

        [Required]
        [Display(Name = "Curso")]
        public string Course { get; set; }

        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Required]
        public List<ScoreDetails> Details { get; set; }

        [Required]
        public double Score { get; set; }
    }

    public class ScoreDetails
    {
        [Required]
        public int IdDetail { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public int Percentaje { get; set; }

        [Required]
        public double Score { get; set; }
    }

    public class ScoreEditModel
    {
        [Required]
        public int ScoreId { get; set; }

        [Required]
        public int IdDetail { get; set; }

        [Required]
        public double Score { get; set; }
    }
}

Proyecto/Controllers/ScoresController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Proyecto.CustomFilters;
using Proyecto.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace Proyecto.Controllers
{
    [Authorize]
    public class ScoresController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private Context db = new Context();
        private LogAlerts log = new LogAlerts();

        public ScoresController()
        {

        }

        public ScoresController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Scores
        [Authorize(Roles = "PROFESSOR")]
        public ActionResult Index()
        {
            string query = "Select * from Schedules where ProfessorId='" + User.Identity.GetUserId().ToString() + "'";
            var schedules=db.Database.SqlQuery<Schedule>(query);
            var list = new List<ScheduleViewModel>();
            foreach(var schedule in schedules.ToList())
            {
                var course = db.Course.SingleOrDefault(e => e.CourseId == schedule.CourseId);
                var custom = new ScheduleViewModel
                {
                    IdSchedule=schedule.IdSchedule,
                    Name=course.Name,
                    Day=schedule.Day,
                    StartTime=schedule.StartTime,
                    EndTime=schedule.EndTime,
                    Students=schedule.Students
                };
                list.Add(custom);
            }
            return View(list);
        }

        [Authorize(Roles = "PROFESSOR, ADMIN")]
        public ActionResult Students(int? id)
        {
            string message;
            var enrollments = db.Enrrollment.ToList();
            var list = new List<StudentViewModel>();
            if (id==null)
            {
                message = DateTime.Now + " El id del horario estaba vació, Acción: Scores/Students";
                log.LogError(message);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var exist = db.Schedule.SingleOrDefault(e => e.IdSchedule == id);
            if(exist==null)
            {
                message = DateTime.Now + " El id del horario no se encontró, Acción: Scores/Students";
                log.LogError(message);
                return HttpNotFound();
            }
            foreach (var enrollment in enrollments) 
            {
                string query = "Select * from EnrollmentDetails where IdEnrollment=" + enrollment.IdEnrollment;
                var details = db.Database.SqlQuery<EnrollmentDetail>(query);
                foreach(var detail in details.ToList())
                {
                    if(detail.IdSchedule==id)
                    {
                        var user = db.AspUser.SingleOrDefault(e => e.Id == enrollment.StudentId);
                        var userData = db.UserData.SingleOrDefault(e => e.idUser == enrollment.StudentId);
                        var score = db.Score.SingleOrDefault(e => e.StudentId == enrollment.StudentId && e.IdSchedule == id);
                        var custom = new StudentViewModel
                        {
                            StudentId=user.Id,
                            ScheduleId=detail.IdSchedule,
                            Name=userData.Name+" "+userData.LastName,
                            Email=user.Email,
                            Phone=user.PhoneNumber,
                            ScoreId=score.IdScore
                        };
                        list.Add(custom);
                    }
                }
            }
            return View(list);
        }

        public ActionResult Details(int? id) 
        {
            string message;
            if(id==null)
            {
                message = DateTime.Now + " El id de la nota estaba vació, Acción: Scores/Details";
                log.LogError(message);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var score = db.Score.SingleOrDefault(e => e.IdScore == id);
            if(score==null)
            {
                message = DateTime.Now + " El id de la nota no se encontró, Acción: Scores/Details";
                log.LogError(message);
                return HttpNotFound();
            }
            var user = db.UserData.SingleOrDefault(e => e.idUser == score.StudentId);
            var schedule = db.Schedule.SingleOrDefault(e => e.IdSchedule == score.IdSchedule);
            var course = db.Course.SingleOrDefault(e => e.CourseId == schedule.IdSchedule);
            var custom = new ScoreViewModel
            {
                ScoreId = score.IdScore,
                Course = course.Name + "(" + schedule.Day + " " + schedule.StartTime + "-" + schedule.EndTime + ")",
                Name = user.Name + " " + user.LastName,
                Details = new List<ScoreDetails>(),
                Score = score.StudentScore
            };
            var query = "Select * from ScoreDetails where IdScore=" + score.IdScore;
            var details=db.Database.SqlQuery<ScoreDetail>(query);
            foreach(var detail in details.ToList())
            {
                var d = new ScoreDetails
                {
                    IdDetail = detail.IdDetail,
                    Name = detail.Name,
                    Score = detail.Score,
                    Percentaje = detail.Percentage
                };
                custom.Details.Add(d);
            }
            return View(custom);
        }

        [Authorize(Roles = "PROFESSOR")]
        public ActionResult Edit(int? idScore, int? idDetail)
        {
            var score = db.Score.SingleOrDefault(e => e.IdScore == idScore);
            var detail = db.ScoreDetail.SingleOrDefault(e => e.IdScore == idScore && e.IdDetail == idDetail);
            var model = new ScoreEditModel
            {
                ScoreId = score.IdScore,
                IdDetail = detail.IdDetail,
                Score=detail.Score
            };
            return View(model);
        }

        [Authorize(Roles = "PROFESSOR")]
        [HttpPost]
        public ActionResult Edit(ScoreEditModel model)
        {
            string message;
            if (!ModelState.IsValid)
            {
                message = DateTime.Now + " Error en los parametros, Acción: Scores/Edit";
                log.LogError(message);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var detail = db.ScoreDetail.SingleOrDefault(e => e.IdScore == model.ScoreId && e.IdDetail == model.IdDetail);
            detail.Score = model.Score;
            var s = db.Score.SingleOrDefault(e => e.IdScore == model.ScoreId);
            var user = db.AspUser.SingleOrDefault(e => e.Id == s.StudentId);
            try
            {
                db.Entry(detail).State = EntityState.Modified;
                db.SaveChanges();
                message = DateTime.Now + " La nota del usuario: " + user.Email + " fue modificada";
                log.LogAlert(message);
            }
            catch (Exception ex) 
            {
                message = DateTime.Now + " Error al editar nota: " + ex;
                log.LogError(message);
                throw ex;
            }
            string query = "Select * from ScoreDetails where IdScore=" + model.ScoreId;
            var details=db.Database.SqlQuery<ScoreDetail>(query);
            double suma = 0;
            foreach(var d in details.ToList())
            {
                suma += d.Score * d.Percentage;
            }
            if((suma/100)>100)
            {
                suma = 100;
                s.StudentScore = suma;
            }
            else
            {
                s.StudentScore = suma / 100;
            }
            db.Entry(s).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect("https://localhost:44302/Scores/Details/" + model.ScoreId);
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult Delete(int id)
        {
            var score = db.Score.SingleOrDefault(e => e.IdScore == id);
            var schedule = db.Schedule.SingleOrDefault(e => e.IdSchedule == score.IdSchedule);
            schedule.Students--;
            db.Entry(schedule).State = EntityState.Modified;
            db.SaveChanges();
            string query = "Select * from Enrollments where StudentId='" + score.StudentId + "'";
            var enrollments = db.Database.SqlQuery<Enrollment>(query);
            foreach (var enrollment in enrollments.ToList())
            {
                query = "Delete from EnrollmentDetails where IdEnrollment=" + enrollment.IdEnrollment + " and IdSchedule=" + score.IdSchedule;
                db.Database.ExecuteSqlCommand(query);
                db.SaveChanges();
                query= "Select * from EnrollmentDetails where IdEnrollment=" + enrollment.IdEnrollment;
                var details = db.Database.SqlQuery<EnrollmentDetail>(query);

Proyecto/Views/Scores/Details.cshtml
@model  Proyecto.Models.ScoreViewModel
@{
    ViewBag.Title = "Students List";
    int i = 1;
}

<main>
    <div class="container" style="margin-top: 50px;">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <h4>Nota de @Model.Name, curso: @Model.Course</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead class="bg-primary text-white">
                                <tr>
                                    <th>
                                        Rubro
                                    </th>
                                    <th>
                                        Nota
                                    </th>
                                    <th>
                                        Porcentaje
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Details.ToList())
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Score)
                                        </td>
                                        <td>
                                            @item.Percentaje%
                                        </td>
                                        @if (Session["Rol"].ToString() == "PROFESSOR")
                                        {
                                            <td>
                                                <a href="/Scores/Edit/?idScore=@Model.ScoreId&idDetail=@item.IdDetail" class="btn btn-success">Editar</a>
                                            </td>
                                        }
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td>
                                        Nota Ponderada: @Model.Score
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

Proyecto/Views/Scores/Edit.cshtml
@model Proyecto.Models.ScoreEditModel
@{
    ViewBag.Title = "Score Edit";
}

<main>
    <div style="margin-top: 50px;">
        @using (Html.BeginForm("Edit", "Scores", FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            <div id="details">
                <div class="row">
                    <div class="col">
                        <div class="card-header">
                            <h4>Editar Nota</h4>
                            <hr />
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            @Html.HiddenFor(m => m.ScoreId)
                            @Html.HiddenFor(m => m.IdDetail)
                        </div>
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Score, new { @class = "form-label" })
                                    <br />
                                    <input type="number" name="Score" id="Score" required min="0" max="100" value="@Model.Score" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="actions" class="py-4 mb-4 bg-light">
                <div class="container">
                    <div class="row">
                        <div class="d-grid col-md-2 mx-auto">
                            <a class="btn btn-secondary btn-block" href="/Scores/Details/@Model.ScoreId">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
                                </svg> Regresar
                            </a>
                        </div>
                        <div class="d-grid col-md-2 mx-auto">
                            <button type="submit" class="btn btn-success btn-block" name="save">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z" />
                                </svg> Guardar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</main>

Proyecto/Views/Scores/Index.cshtml
@model IEnumerable<Proyecto.Models.ScheduleViewModel>
@{
    ViewBag.Title = "Professor Schedules";
}

<main>
    <div class="container" style="margin-top: 50px;">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <h4>Lista de Cursos</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead class="bg-primary text-white">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Day)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.StartTime)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.EndTime)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Students)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Day)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StartTime)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EndTime)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Students)
                                        </td>
                                        @if (item.Students != 0)
                                        {
                                            <td>
                                                <a href="/Scores/Students/@item.IdSchedule" class="btn btn-primary">Ver Estudiantes</a>
                                            </td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

Proyecto/Views/Scores/Students.cshtml
@model IEnumerable<Proyecto.Models.StudentViewModel>
@{
    ViewBag.Title = "Students List";
}

<main>
    <div class="container" style="margin-top: 50px;">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <h4>Lista de Estudiantes</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead class="bg-primary text-white">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Phone)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Phone)
                                        </td>
                                        <td>
                                            <a href="/Scores/Details/@item.ScoreId" class="btn btn-primary">Ver Nota</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>